swagger: '2.0'
info:
  version: 1.0.0
  title: 'NIO API'
host: 'localhost:10010'
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /ping:
    x-swagger-router-controller: ping
    get:
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Object'
  /retrieveQuote:
    x-swagger-router-controller: retrieveQuote
    get:
      description: 'Retrieve a quote by id'
      parameters:
        -
          name: id
          in: query
          description: 'The id of the quote'
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Object'
definitions:
  Message:
    required:
      - message
    properties:
      message:
        type: string
  Object:
    type: object
    properties:
      name:
        type: string
