swagger: '2.0'
info:
  version: 1.0.0
  title: 'NIO API'
host: 'localhost:10010'
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /ping:
    x-swagger-router-controller: ping
    get:
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Object'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Error'
  /retrieveQuote:
    x-swagger-router-controller: noop
    get:
      description: 'Retrieve quote by id'
      parameters:
        -
          name: id
          in: query
          description: 'The id of the quote'
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Object'
  /saveQuote:
    x-swagger-router-controller: noop
    post:
      description: 'Save quote'
      parameters:
        -
          name: id
          in: query
          description: 'The id of the quote'
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Object'
  /validateAddress:
    x-swagger-router-controller: ping
    get:
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Object'
definitions:
  Message:
    required:
      - message
    properties:
      message:
        type: string
  Object:
    type: object
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
